route_planner:
  ros__parameters:
    config_yaml_path: routes/inagi/route_config.yaml
    csv_base_dir: routes/inagi
    map_image_path: routes/inagi/map/gsi20251028132330203.png
    map_worldfile_path: routes/inagi/map/gsi20251028132330203_corr.pgw
    projection_id: tokyo_station
    datum: WGS84
    map_frame_id: map
    earth_frame_id: earth
    origin_latitude: 35.681382
    origin_longitude: 139.766084
    origin_altitude: 3.86
    map_yaw_offset_rad: 0.0
