/ypspur_node:
  ros__parameters:
    cmd_vel_timeout_s: 0.5      # cmd_vel が止まったら自動停止
    odom_publish_hz: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    coordinate_system: 2        # 0=BS, 1=SP, 2=GL, 3=LC, 4=FS, 5=BL
    ipc:
      use_socket: false
      ip: 127.0.0.1
      port: 54321
    velocity_max:
      linear: 1.0               # m/s, ±対称
      angular: 1.5              # rad/s, ±対称
