traffic_signal_recognizer:
  ros__parameters:
    recog_flag_topic: /recog_flag
    detections_topic: /perception/traffic_signal/detections
    image_topic: /usb_cam/image_raw
    sig_recog_topic: /sig_recog
    sig_det_image_topic: /sig_det_imgs
    confidence_threshold: 0.8
    judge_count: 3
    go_status: 1
    stop_status: 2
    unknown_class_id: 99
    green_class_ids: [1]
    red_class_ids: [0]
    green_class_names: ['green']
    red_class_names: ['red']
    hold_go: false
    publish_stop_when_disabled: false
    publish_image_when_disabled: true
